const G='../star-athletes-draco-lab/generated/';const REV='412';
const cv=document.getElementById('cv'),ctx=cv.getContext('2d'),st=document.getElementById('st');
const defs={horn:[['normal','ノーマル'],['curl','カール'],['crystal','クリスタル']],wing:[['normal','ノーマル'],['feather','フェザー'],['crystal','クリスタル']],tail:[['normal','ノーマル'],['star','スター'],['leaf','リーフ']]};
let cat='horn',variant='normal',slot='horn_left',body,part,info;
const T={horn_left:{dx:0,dy:0,s:1,r:0,fx:false,fy:false},horn_right:{dx:0,dy:0,s:1,r:0,fx:true,fy:false},wing_left:{dx:0,dy:0,s:1,r:0,fx:false,fy:false},wing_right:{dx:0,dy:0,s:1,r:0,fx:true,fy:false},tail:{dx:0,dy:0,s:1,r:0,fx:true,fy:false}};
const $=id=>document.getElementById(id);const els={dx:$('dx'),dy:$('dy'),sc:$('sc'),rot:$('rot'),op:$('op'),fx:$('fx'),fy:$('fy')};
function load(src){return new Promise((ok,no)=>{const im=new Image();im.onload=()=>ok(im);im.onerror=no;im.src=src})}
function slotList(){return cat==='horn'?[['horn_left','左角'],['horn_right','右角']]:cat==='wing'?[['wing_left','左羽'],['wing_right','右羽']]:[['tail','しっぽ']]}
async function loadPart(){part=await load(variant==='normal'?G+'ref_'+slot+'.png?v='+REV:G+cat+'_'+variant+'_clean.png?v='+REV)}
function buttons(){const vars=$('vars'),slots=$('slots');vars.innerHTML='';for(const [v,l] of defs[cat]){const b=document.createElement('button');b.textContent=l;b.className=v===variant?'on':'';b.onclick=async()=>{variant=v;await loadPart();buttons();sync();render()};vars.appendChild(b)}slots.innerHTML='';for(const [s,l] of slotList()){const b=document.createElement('button');b.textContent=l;b.className=s===slot?'on':'';b.onclick=async()=>{slot=s;await loadPart();buttons();sync();render()};slots.appendChild(b)}}
function sync(){const t=T[slot];els.dx.value=t.dx;els.dy.value=t.dy;els.sc.value=t.s;els.rot.value=t.r;els.fx.checked=t.fx;els.fy.checked=t.fy;$('vdx').textContent=t.dx.toFixed(3);$('vdy').textContent=t.dy.toFixed(3);$('vsc').textContent=t.s.toFixed(2);$('vrot').textContent=Math.round(t.r)+'°';$('vop').textContent=(+els.op.value).toFixed(2);$('mode').textContent=variant==='normal'?'NORMAL = exact reference':'VARIANT fit → '+slot;const a=info.references[slot].anchor;$('meta').innerHTML='<div><b>'+slot+'</b><br>x '+a.x.toFixed(4)+' / y '+a.y.toFixed(4)+'</div><div><b>base scale</b><br>'+a.scale.toFixed(4)+'</div>'}
function render(){ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(body,0,0);const r=info.references[slot].rect,t=T[slot];if(variant==='normal'){ctx.save();ctx.globalAlpha=+els.op.value;ctx.drawImage(part,r[0],r[1]);ctx.restore()}else{const sw=r[2]-r[0],sh=r[3]-r[1],s=Math.min(sw/part.naturalWidth,sh/part.naturalHeight)*t.s,w=part.naturalWidth*s,h=part.naturalHeight*s,cx=(r[0]+r[2])/2+t.dx*cv.width,cy=(r[1]+r[3])/2+t.dy*cv.height;ctx.save();ctx.translate(cx,cy);ctx.rotate(t.r*Math.PI/180);ctx.scale(t.fx?-1:1,t.fy?-1:1);ctx.globalAlpha=+els.op.value;ctx.drawImage(part,-w/2,-h/2,w,h);ctx.restore()}ctx.save();ctx.strokeStyle='rgba(38,92,136,.55)';ctx.setLineDash([6,5]);ctx.strokeRect(r[0]+.5,r[1]+.5,r[2]-r[0]-1,r[3]-r[1]-1);ctx.restore()}
$('cats').onclick=async e=>{const b=e.target.closest('button');if(!b)return;cat=b.dataset.cat;variant='normal';slot=slotList()[0][0];await loadPart();document.querySelectorAll('#cats button').forEach(x=>x.classList.toggle('on',x.dataset.cat===cat));buttons();sync();render()};
for(const k of ['dx','dy','sc','rot'])els[k].oninput=()=>{const m={dx:'dx',dy:'dy',sc:'s',rot:'r'};T[slot][m[k]]=+els[k].value;sync();render()};els.fx.onchange=()=>{T[slot].fx=els.fx.checked;sync();render()};els.fy.onchange=()=>{T[slot].fy=els.fy.checked;sync();render()};els.op.oninput=()=>{sync();render()};
(async()=>{try{info=await fetch(G+'metadata.json?v=411').then(r=>r.json());body=await load(G+'body_stage.png?v=411');cv.width=info.body_stage.width;cv.height=info.body_stage.height;await loadPart();buttons();sync();render();st.textContent='Variant fitting ready / 412'}catch(e){st.textContent='読込失敗'}})();