const G='../star-athletes-draco-lab/generated/';const REV='413';
const cv=document.getElementById('cv'),ctx=cv.getContext('2d'),st=document.getElementById('st');
const defs={horn:[['normal','ノーマル'],['curl','カール'],['crystal','クリスタル']],wing:[['normal','ノーマル'],['feather','フェザー'],['crystal','クリスタル']],tail:[['normal','ノーマル'],['star','スター'],['leaf','リーフ']]};
let cat='horn',variant='normal',slot='horn_left',body,part,info,presets={};let current={dx:0,dy:0,s:1,r:0,fx:false,fy:false};
const $=id=>document.getElementById(id),els={dx:$('dx'),dy:$('dy'),sc:$('sc'),rot:$('rot'),op:$('op'),fx:$('fx'),fy:$('fy')};
function load(src){return new Promise((ok,no)=>{const im=new Image();im.onload=()=>ok(im);im.onerror=no;im.src=src})}
function slots(){return cat==='horn'?[['horn_left','左角'],['horn_right','右角']]:cat==='wing'?[['wing_left','左羽'],['wing_right','右羽']]:[['tail','しっぽ']]}
function fixed(){if(variant==='normal')return{dx:0,dy:0,s:1,r:0,fx:false,fy:false};const p=presets?.[slot]?.[variant];return p?{dx:p.dx,dy:p.dy,s:p.scale,r:p.rotation,fx:p.flipX,fy:p.flipY}:{dx:0,dy:0,s:1,r:0,fx:false,fy:false}}
async function loadPart(){if(variant==='normal')return part=await load(G+'ref_'+slot+'.png?v='+REV);if(cat==='horn'){const side=slot.endsWith('_left')?'left':'right';return part=await load(G+'horn_'+variant+'_'+side+'.png?v='+REV)}part=await load(G+cat+'_'+variant+'_clean.png?v='+REV)}
function mkButtons(){const v=$('vars'),s=$('slots');v.innerHTML='';for(const [id,label] of defs[cat]){const b=document.createElement('button');b.textContent=label;b.className=id===variant?'on':'';b.onclick=async()=>{variant=id;current=fixed();await loadPart();mkButtons();sync();render()};v.appendChild(b)}s.innerHTML='';for(const [id,label] of slots()){const b=document.createElement('button');b.textContent=label;b.className=id===slot?'on':'';b.onclick=async()=>{slot=id;current=fixed();await loadPart();mkButtons();sync();render()};s.appendChild(b)}}
function sync(){const t=current;els.dx.value=t.dx;els.dy.value=t.dy;els.sc.value=t.s;els.rot.value=t.r;els.fx.checked=t.fx;els.fy.checked=t.fy;$('vdx').textContent=t.dx.toFixed(3);$('vdy').textContent=t.dy.toFixed(3);$('vsc').textContent=t.s.toFixed(2);$('vrot').textContent=Math.round(t.r)+'°';$('vop').textContent=(+els.op.value).toFixed(2);$('mode').textContent=variant==='normal'?'NORMAL = exact reference':'FIXED PRESET → '+slot+' / '+variant;const a=info.references[slot].anchor;$('meta').innerHTML='<div><b>'+slot+'</b><br>x '+a.x.toFixed(4)+' / y '+a.y.toFixed(4)+'</div><div><b>fixed</b><br>dx '+t.dx.toFixed(3)+' / dy '+t.dy.toFixed(3)+'<br>scale '+t.s.toFixed(2)+' / rot '+Math.round(t.r)+'°<br>flipX '+t.fx+'</div>'}
function render(){ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(body,0,0);const r=info.references[slot].rect,t=current;if(variant==='normal'){ctx.save();ctx.globalAlpha=+els.op.value;ctx.drawImage(part,r[0],r[1]);ctx.restore()}else{const sw=r[2]-r[0],sh=r[3]-r[1],k=Math.min(sw/part.naturalWidth,sh/part.naturalHeight)*t.s,w=part.naturalWidth*k,h=part.naturalHeight*k,cx=(r[0]+r[2])/2+t.dx*cv.width,cy=(r[1]+r[3])/2+t.dy*cv.height;ctx.save();ctx.translate(cx,cy);ctx.rotate(t.r*Math.PI/180);ctx.scale(t.fx?-1:1,t.fy?-1:1);ctx.globalAlpha=+els.op.value;ctx.drawImage(part,-w/2,-h/2,w,h);ctx.restore()}ctx.save();ctx.strokeStyle='rgba(38,92,136,.55)';ctx.setLineDash([6,5]);ctx.strokeRect(r[0]+.5,r[1]+.5,r[2]-r[0]-1,r[3]-r[1]-1);ctx.restore()}
$('cats').onclick=async e=>{const b=e.target.closest('button');if(!b)return;cat=b.dataset.cat;variant='normal';slot=slots()[0][0];current=fixed();await loadPart();document.querySelectorAll('#cats button').forEach(x=>x.classList.toggle('on',x.dataset.cat===cat));mkButtons();sync();render()};
for(const k of ['dx','dy','sc','rot'])els[k].oninput=()=>{current[{dx:'dx',dy:'dy',sc:'s',rot:'r'}[k]]=+els[k].value;sync();render()};els.fx.onchange=()=>{current.fx=els.fx.checked;sync();render()};els.fy.onchange=()=>{current.fy=els.fy.checked;sync();render()};els.op.oninput=()=>{sync();render()};
(async()=>{try{[info,presets]=await Promise.all([fetch(G+'metadata.json?v=411').then(r=>r.json()),fetch(G+'variant_presets.json?v='+REV).then(r=>r.json())]);body=await load(G+'body_stage.png?v=411');cv.width=info.body_stage.width;cv.height=info.body_stage.height;current=fixed();await loadPart();mkButtons();sync();render();st.textContent='Fixed variant presets active / 413'}catch(e){console.error(e);st.textContent='読込失敗'}})();