const V='0.9.5';
const $=id=>document.getElementById(id), rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const SP={draco:['ドラコ族','🐲',{power:18,guts:14,stamina:8}],unil:['ユニル族','🦄',{speed:18,agility:14,tech:7}],grimo:['グリモ族','🦅',{tech:18,agility:14,speed:5}],puru:['ぷるもん族','🫧',{stamina:16,tech:8}]};
const SL={power:'ちから',speed:'スピード',stamina:'スタミナ',agility:'すばやさ',tech:'テクニック',guts:'こんじょう'};
const R=['C','U','R','SR','SSR','UR','EX'], COL=['赤','青','緑','白','黒','黄','金'], PAT=['なし','縞','斑点','炎','雷','星'], ACC=['なし','🎀','🥽','🎗️','🔔','⭐'];
const PART={draco:['小角','二本角','丸角','星角'],unil:['短角','長角','螺旋角','星角'],grimo:['小羽','丸羽','長羽','星羽'],puru:['丸耳','しずく耳','星耳','ふわ耳']};
const P=['熱血','冷静','負けず嫌い','お調子者','臆病','マイペース'];
const ART={draco:'../star-athletes/assets/draco.svg?v=095',unil:'../star-athletes/assets/unil.svg?v=095',grimo:'../star-athletes/assets/grimo.svg?v=095',puru:'../star-athletes/assets/puru.svg?v=095'};
const INF={'50m走':['スピード・すばやさ','speed'],'障害物競走':['テクニック・すばやさ','tech'],'大玉ころがし':['ちから・スタミナ','power'],'坂道かけあがり':['ちから・スタミナ・こんじょう','stamina'],'10000m走':['スタミナ・こんじょう','stamina'],'的当て':['テクニック・ちから','tech'],'リレー':['スピード・テクニック・連携','speed'],'綱引き':['ちから・スタミナ・連携','power']};
let S={starters:[],nest:[],lineage:[],released:[],cands:[],parents:[],egg:null,sel:[],wins:0,turn:0,foster:[],dex:{b:0,a:0,f:0,r:0,rel:0},schedule:[],plans:{},assign:{},strat:{}};
function breedingCap(){
  const rank=Math.max(0,Math.min(5,Number(S.leagueRank)||0));
  if(rank>=1)return Math.min(10,5+rank);
  if(S.localPromotionEnteredCap)return 5;
  if(S.localFirstWinCap||Number(S.leagueWins?.['ローカル'])>0)return 4;
  return 3;
}
const cap=()=>breedingCap(), poolCap=()=>Math.min(18,8+Math.floor(S.wins/2)), ri=x=>R.indexOf(x);
function visual(sp){return{color:COL[rnd(0,6)],pattern:PAT[rnd(0,5)],acc:ACC[rnd(0,5)],part:PART[sp][rnd(0,3)]}}
function monster(sp,name,gen=0){let st={};for(let k in SL)st[k]=90+rnd(-8,8)+(SP[sp][2][k]||0);return{id:crypto.randomUUID(),name,species:sp,rarity:'C',gen,stats:st,personality:P[rnd(0,5)],visual:visual(sp),origin:'プレゼント',rivalCount:0}}
function baby(a,b){let sp=Math.random()<.5?a.species:b.species,st={};for(let k in SL){let av=(a.stats[k]+b.stats[k])/2,hi=Math.max(a.stats[k],b.stats[k]);st[k]=Math.round(av*.78+hi*.22+rnd(-8,10)+(SP[sp][2][k]||0)*.2)}let v={};for(let k of ['color','pattern','acc','part'])v[k]=Math.random()<.48?a.visual[k]:Math.random()<.96?b.visual[k]:visual(sp)[k];return{id:crypto.randomUUID(),name:SP[sp][0].slice(0,2)+rnd(10,99),species:sp,rarity:'C',gen:Math.max(a.gen,b.gen)+1,stats:st,personality:P[rnd(0,5)],visual:v,origin:a.name+'×'+b.name,rivalCount:0}}
function avatar(m,big=false){return `<div class="avatar art ${big?'bigArt':''}"><img class="artimg" src="${ART[m.species]}" alt="${SP[m.species][0]}"><div class="accessory">${m.visual.acc==='なし'?'':m.visual.acc}</div></div>`}
function stats(m){return Object.entries(m.stats).map(([k,v])=>`<span>${SL[k]} <b>${v}</b></span>`).join('')}
function breederPool(){let x=[...S.starters,...S.lineage,...S.nest],map=new Map();x.forEach(m=>map.set(m.id,m));return [...map.values()]}
function card(m,mode){let on=mode==='p'&&S.parents.includes(m.id)||mode==='c'&&S.sel.includes(m.id);return `<div class="card ${on?'sel':''}" data-id="${m.id}" data-mode="${mode}">${avatar(m)}<div class="bd"><div class="nm"><b>${m.name}</b></div><div class="sm speciesLine">${SP[m.species][0]} / G${m.gen} / ${m.personality}</div><div class="traitRow"><span>${m.visual.pattern}</span><span>${m.visual.part}</span></div><div class="miniStats">${stats(m)}</div><div class="tags">${m.visual.color}・${m.visual.pattern}・${m.visual.part}</div></div></div>`}
function makeSchedule(){let a=['50m走','障害物競走','大玉ころがし','坂道かけあがり','10000m走','的当て'].sort(()=>Math.random()-.5).slice(0,3);a.push(Math.random()<.5?'リレー':'綱引き');S.schedule=a}
function score(m,e){let s=m.stats;return e==='50m走'?s.speed*.5+s.agility*.3+s.tech*.2:e==='障害物競走'?s.tech*.4+s.agility*.35+s.speed*.15+s.guts*.1:e==='大玉ころがし'?s.power*.48+s.stamina*.3+s.guts*.22:e==='坂道かけあがり'?s.power*.35+s.stamina*.35+s.guts*.3:e==='10000m走'?s.stamina*.45+s.guts*.3+s.speed*.15+s.tech*.1:e==='的当て'?s.tech*.55+s.power*.2+s.agility*.15+s.guts*.1:e==='リレー'?s.speed*.45+s.tech*.2+s.agility*.2+s.guts*.15:s.power*.45+s.stamina*.3+s.guts*.25}
const best=e=>[...S.nest].sort((a,b)=>score(b,e)-score(a,e))[0];
function pickParent(id){S.parents.includes(id)?S.parents=S.parents.filter(x=>x!==id):S.parents.length<2?S.parents.push(id):S.parents=[S.parents[1],id];render()}
function pickCand(id){S.sel.includes(id)?S.sel=S.sel.filter(x=>x!==id):S.sel.length<3&&S.sel.push(id);render()}
function release(id){let m=S.lineage.find(x=>x.id===id);if(!m)return;S.lineage=S.lineage.filter(x=>x.id!==id);S.released.push(m);S.dex.rel++;render()}
function renderLineage(){$('poolCount').textContent=S.lineage.length;$('poolCap').textContent=poolCap();$('lineagePool').innerHTML=S.lineage.length?S.lineage.map(m=>`<div class="card">${avatar(m)}<div class="bd"><div class="nm"><b>${m.name}</b><em>${m.rarity}</em></div><div class="sm">${SP[m.species][0]} / G${m.gen}</div><button class="btn tiny" data-release="${m.id}">リリース</button></div></div>`).join(''):'<div class="sm">まだ過去世代はいません。</div>';document.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>release(b.dataset.release))}
function renderTrain(){if(!S.nest.length||!S.schedule.length)return;$('sched').innerHTML=S.schedule.map(e=>`<span class="chip"><b>${e}</b><br>${INF[e][0]}</span>`).join('');$('plans').innerHTML=S.nest.map(m=>{let cur=S.plans[m.id]||INF[S.schedule[0]][1];return `<div class="trainCard">${avatar(m)}<div><b>${m.name}</b><div class="statGrid">${stats(m)}</div><select data-plan="${m.id}">${[['speed','走り込み'],['power','パワー'],['tech','技術'],['stamina','持久'],['team','連携']].map(([v,n])=>`<option value="${v}" ${cur===v?'selected':''}>${n}</option>`).join('')}</select></div></div>`}).join('');document.querySelectorAll('[data-plan]').forEach(x=>x.onchange=()=>S.plans[x.dataset.plan]=x.value);$('prep').innerHTML=S.schedule.map((e,i)=>{let b=best(e);S.assign[i]??=b.id;S.strat[i]??='バランス';return `<div class="evt"><b>${e}</b><div class="sm">重要：${INF[e][0]} / おすすめ：${b.name}</div><select data-a="${i}">${S.nest.map(m=>`<option value="${m.id}" ${m.id===S.assign[i]?'selected':''}>${m.name}</option>`).join('')}</select><select data-s="${i}">${['先行','バランス','温存','追込'].map(z=>`<option ${z===S.strat[i]?'selected':''}>${z}</option>`).join('')}</select></div>`}).join('');document.querySelectorAll('[data-a]').forEach(x=>x.onchange=()=>S.assign[x.dataset.a]=x.value);document.querySelectorAll('[data-s]').forEach(x=>x.onchange=()=>S.strat[x.dataset.s]=x.value)}
function render(){ $('w').textContent=S.wins;$('cap').textContent=$('mx').textContent=cap();$('cnt').textContent=S.cands.length;$('turn').textContent=S.turn;$('doTrain').disabled=S.turn>=3;$('toMeet').disabled=S.turn<3;$('breeders').innerHTML=breederPool().map(m=>card(m,'p')).join('');$('cands').innerHTML=S.cands.map(m=>card(m,'c')).join('');document.querySelectorAll('[data-mode="p"]').forEach(x=>x.onclick=()=>pickParent(x.dataset.id));document.querySelectorAll('[data-mode="c"]').forEach(x=>x.onclick=()=>pickCand(x.dataset.id));$('breedBtn').disabled=S.parents.length!==2||!!S.egg||S.cands.length>=cap();$('hatch').disabled=!S.egg;$('candBox').classList.toggle('hide',S.cands.length<cap());$('adopt').disabled=S.sel.length!==3;$('db').textContent=S.dex.b;$('da').textContent=S.dex.a;$('df').textContent=S.dex.f;$('dr').textContent=S.dex.r;$('drel').textContent=S.dex.rel;$('fl').innerHTML=S.foster.length?S.foster.slice(-8).reverse().map(m=>`${m.name} 再会${m.rivalCount||0}回`).join('<br>'):'まだいません';renderLineage();renderTrain();let bp=breederPool();[$('pa'),$('pb')].forEach((e,i)=>{let m=bp.find(x=>x.id===S.parents[i]);e.innerHTML=m?`${avatar(m)}<b>${m.name}</b>`:(i?'②親':'①親')})}
$('breedBtn').onclick=()=>{let [a,b]=S.parents.map(id=>breederPool().find(x=>x.id===id));S.egg=baby(a,b);$('egg').innerHTML='<div class="eggPulse">🥚</div><div class="sparkRing">✦　✦　✦</div>';$('birth').innerHTML='<div class="sm hatchHint">卵が動いている…！</div>';render()};
$('hatch').onclick=()=>{let b=S.egg;if(!b)return;S.cands.push(b);S.dex.b++;S.egg=null;S.parents=[];$('egg').innerHTML='✨';$('birth').innerHTML=`<div class="hatchReveal"><div class="newbornLabel">NEW ATHLETE!</div>${avatar(b,true)}<div class="hatchName"><b>${b.name}</b></div><div class="hatchMeta">${SP[b.species][0]} ・ G${b.gen} ・ ${b.personality}</div><div class="traitRow hatchTraits"><span>${b.visual.pattern}</span><span>${b.visual.part}</span></div><div class="hatchStats">${Object.entries(b.stats).map(([k,v])=>`<div><span>${SL[k]}</span><b>${v}</b></div>`).join('')}</div><div class="inheritBox"><b>継承</b><br>親：${b.origin}<br>見た目：${b.visual.color} / ${b.visual.pattern} / ${b.visual.part}${b.visual.acc!=='なし'?' / '+b.visual.acc:''}</div></div>`;render()};
$('adopt').onclick=()=>{let chosen=S.cands.filter(m=>S.sel.includes(m.id)),left=S.cands.filter(m=>!S.sel.includes(m.id));left.forEach(m=>S.foster.push(m));S.dex.f+=left.length;S.dex.a+=3;S.nest.forEach(m=>{if(!S.lineage.some(x=>x.id===m.id))S.lineage.push(m)});S.nest=chosen;S.cands=[];S.sel=[];S.parents=[];S.turn=0;S.plans={};S.assign={};S.strat={};makeSchedule();show('train');render()};
$('doTrain').onclick=()=>{if(S.turn>=3)return;let B={speed:[['speed',12],['agility',7]],power:[['power',12],['guts',7]],tech:[['tech',12],['agility',6]],stamina:[['stamina',12],['guts',6]],team:[['guts',7],['tech',7]]},out=[];S.nest.forEach(m=>{let t=S.plans[m.id]||'speed',r=Math.random(),grade=r<.02?'超成功':r<.15?'大成功':'成功',mul=grade==='超成功'?2:grade==='大成功'?1.5:1,up=[];B[t].forEach(([k,v])=>{let n=Math.round(v*mul+rnd(-1,3));m.stats[k]+=n;up.push(`${SL[k]}+${n}`)});out.push(`<b>${m.name}：${grade}</b> ${up.join(' / ')}`)});S.turn++;$('gain').innerHTML='<div class="notice">'+out.join('<br>')+'</div>';render()};
$('toMeet').onclick=()=>{if(S.turn<3)return;$('events').innerHTML=S.schedule.map((e,i)=>`<div class="evt"><b>${e}</b><div>${S.nest.find(m=>m.id===S.assign[i])?.name||best(e).name} / ${S.strat[i]}</div></div>`).join('');show('meet')};
// Tournament execution and season/generation progression are owned by patch-v225/patch-v233.
function show(id){['breed','train','meet','dex'].forEach(x=>$(x).classList.toggle('hide',x!==id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.v===id))}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>show(t.dataset.v));
$('reloadBtn').onclick=()=>{let u=new URL(location.href);u.searchParams.set('v',V+'-'+Date.now());location.replace(u)};
S.starters=[monster('draco','ラゴ'),monster('unil','ミラ')];render();