(()=>{
// v0.24.3 Alpha Lab character/genetics layer that works with current finished-art renderer.
const SAVE243='star-athletes-save-v200';
const COLORS243=['赤','青','緑','白','黒','黄'];
const PAT243=['なし','縞','斑点','炎','雷','星'];
const EXP243=['neutral','happy','competitive','sad','tired','excited','proud'];
const EXPL243={neutral:'🙂',happy:'😊',competitive:'🔥',sad:'😢',tired:'😮‍💨',excited:'🤩',proud:'😤'};
const PARTS243={draco:['horn','wing','tail','muzzle_mark'],unil:['horn','mane','ear','tail'],grimo:['beak','wing','chest_feather','crest'],puru:['ear_blob','tail_blob','transparency_pattern','inner_core']};
function shinyLabel243(m){const names={draco:'エメラルド系',unil:'ミント系',grimo:'パープル系',puru:'ピンク系'};return m?.shiny?`✨色違い（${names[m.species]||'特殊色'}）`:''}
function persist243(){try{localStorage.setItem(SAVE243,JSON.stringify({savedAt:Date.now(),S}))}catch(_){}}
function all243(){const a=[],seen=new Set();for(const k of ['starters','nest','lineage','released','cands','foster'])for(const m of(S[k]||[]))if(m&&!seen.has(m.id)){seen.add(m.id);a.push(m)}if(S.egg&&!seen.has(S.egg.id))a.push(S.egg);return a}
function mut243(m){const n=Number(m?.hidden233?.mutation);if(!Number.isFinite(n))return 0;return [0,0,0,1,2,3,4,5][Math.max(0,Math.min(7,Math.round(n)))]}
function randomPart243(k){return `${k}_${1+Math.floor(Math.random()*4)}`}
function ensure243(m){if(!m)return;m.visual=m.visual||{};m.visual.color=m.visual.color||COLORS243[Math.floor(Math.random()*COLORS243.length)];m.visual.pattern=m.visual.pattern||PAT243[Math.floor(Math.random()*PAT243.length)];if(!m.expression243)m.expression243='neutral';if(!m.expressionTendency243)m.expressionTendency243=m.expression243;if(!m.parts243){m.parts243={};for(const k of(PARTS243[m.species]||[]))m.parts243[k]=randomPart243(k);if(m.visual.part){const first=(PARTS243[m.species]||[])[0];if(first)m.parts243[first]=m.visual.part}}if(m.visual.color==='金'&&!m.rareVisual243)m.rareVisual243='gold';if(m.shiny&&!m.rareVisual243)m.rareVisual243='shiny'}
function pickCat243(a,b,pool,mutationChance){const r=Math.random();if(r<.42)return a;if(r<.84)return b;if(r<1-mutationChance){const x=pool.filter(v=>v!==a&&v!==b);return x.length?x[Math.floor(Math.random()*x.length)]:(Math.random()<.5?a:b)}const x=pool.filter(v=>v!==a&&v!==b);return x.length?x[Math.floor(Math.random()*x.length)]:(Math.random()<.5?a:b)}
function parentPart243(p,sp,k){if(!p||p.species!==sp)return null;ensure243(p);return p.parts243?.[k]||null}
try{const oldBaby243=baby;baby=function(a,b){ensure243(a);ensure243(b);const c=oldBaby243(a,b);ensure243(c);const boost=Math.min(.07,(mut243(a)+mut243(b))*.006),mutationChance=.05+boost;c.visual.color=pickCat243(a.visual.color,b.visual.color,COLORS243,mutationChance);c.visual.pattern=pickCat243(a.visual.pattern,b.visual.pattern,PAT243,mutationChance);c.parts243={};for(const k of(PARTS243[c.species]||[])){const pa=parentPart243(a,c.species,k),pb=parentPart243(b,c.species,k);if(pa&&pb)c.parts243[k]=pickCat243(pa,pb,[pa,pb,randomPart243(k),randomPart243(k)],mutationChance);else c.parts243[k]=pa||pb||randomPart243(k)}const er=Math.random();c.expressionTendency243=er<.42?(a.expressionTendency243||'neutral'):er<.84?(b.expressionTendency243||'neutral'):er<.95?'neutral':EXP243[Math.floor(Math.random()*EXP243.length)];c.expression243='neutral';const rareRoll=Math.random();if(rareRoll<mutationChance*.12){c.visual.color='プリズム';c.rareVisual243='prism'}else if(rareRoll<mutationChance*.38){c.visual.color='金';c.rareVisual243='gold'}else if(Math.random()<mutationChance*.22){c.rareVisual243='mutation'}c.visualGenetics243={father:42,mother:42,middle:Math.max(0,Math.round((1-.84-mutationChance)*100)),mutation:Math.round(mutationChance*100)};return c}}catch(e){console.warn('baby243',e)}
function cardMeta243(card,m){if(!card||!m)return;ensure243(m);const bd=card.querySelector('.bd')||card;let row=card.querySelector('.coreMeta243');if(!row){row=document.createElement('div');row.className='coreMeta243';bd.appendChild(row)}const rare=m.rareVisual243?`<b class="rare243">${m.rareVisual243==='prism'?'🌈 虹色':m.rareVisual243==='gold'?'👑 黄金':m.rareVisual243==='shiny'?'✨ 色違い':'✦ 異変色'}</b>`:'';const parts=Object.values(m.parts243||{}).slice(0,3).join(' / ');row.innerHTML=`<div>${rare}</div><small>${EXPL243[m.expression243]||'🙂'} ${m.visual?.color||''}・${m.visual?.pattern||''}${parts?' / '+parts:''}</small>`;card.classList.toggle('rareCard243',!!m.rareVisual243)}
function shiny243(){const all=all243(),byId=new Map(all.filter(Boolean).map(m=>[m.id,m]));document.querySelectorAll('.card[data-id],.train210[data-athlete210]').forEach(card=>{const id=card.dataset.id||card.dataset.athlete210,m=byId.get(id);let tag=card.querySelector('.shinyColor243');if(!m?.shiny){tag?.remove();return}if(!tag){tag=document.createElement('div');tag.className='shinyColor243';(card.querySelector('.bd')||card.querySelector('header>div')||card).appendChild(tag)}tag.textContent=shinyLabel243(m)});const birth=document.getElementById('birth'),latest=(S.cands||[])[(S.cands||[]).length-1];if(latest?.shiny&&birth?.querySelector('.hatchReveal')){let tag=birth.querySelector('.shinyResult243');if(!tag){tag=document.createElement('div');tag.className='shinyResult243';birth.querySelector('.hatchName')?.after(tag)}tag.textContent=shinyLabel243(latest);const inh=birth.querySelector('.inheritBox');if(inh){const normal=latest.visual?.color||'',parts=[shinyLabel243(latest)+(normal?`（通常色:${normal}）`:''),latest.visual?.pattern,latest.visual?.part].filter(Boolean);if(latest.visual?.acc&&latest.visual.acc!=='なし')parts.push(latest.visual.acc);inh.innerHTML=`<b>継承</b><br>親：${latest.origin||''}<br>見た目：${parts.join(' / ')}`}}else birth?.querySelector('.shinyResult243')?.remove()}
function sync243(){all243().forEach(ensure243);document.querySelectorAll('#breeders .card[data-id],#cands .card[data-id]').forEach(c=>cardMeta243(c,all243().find(m=>m.id===c.dataset.id)));document.querySelectorAll('#lineagePool .card').forEach((c,i)=>cardMeta243(c,(S.lineage||[])[i]));document.querySelectorAll('.train210').forEach(c=>{const old=c.querySelector('.coreMeta243');if(old)old.remove()});shiny243();persist243()}
function late243(){sync243();setTimeout(sync243,40);setTimeout(sync243,160)}
window.STAR_VISUAL243={sync:sync243};
try{const before243=render;render=function(){const out=before243();late243();return out}}catch(e){console.warn('render243',e)}
function animateMeet243(){const txt=document.getElementById('result')?.textContent||'';if(!txt)return;const win=/総合1位|優勝|勝利/.test(txt);(S.nest||[]).forEach(m=>m.expression243=win?'happy':'sad');document.querySelectorAll('.entries210 .avatar,.train210 .avatar').forEach(a=>{a.classList.remove('win243','lose243');void a.offsetWidth;a.classList.add(win?'win243':'lose243')});late243()}
document.addEventListener('click',e=>{if(e.target.closest?.('#run')){setTimeout(animateMeet243,80);setTimeout(animateMeet243,300)}if(e.target.closest?.('.tab[data-v="breed"],#hatch,#adopt'))late243()},false);
const css=document.createElement('style');css.textContent=`.coreMeta243{margin-top:6px;padding-top:5px;border-top:1px dotted #ccd5df}.coreMeta243>div{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.coreMeta243 small{display:block;margin-top:4px;font-size:6px;color:#68788b}.rare243{font-size:6px;background:#fff3a8;border:1px solid #d9b93e;border-radius:999px;padding:3px 5px}.rareCard243{box-shadow:0 0 0 2px #e3c154,0 0 14px #ffd95b66!important}.rareCard243 .avatar{filter:saturate(1.15) drop-shadow(0 0 5px #ffd75a)}.shinyColor243,.shinyResult243{color:#d7548f;font-weight:1000}.shinyColor243{font-size:8px;margin-top:4px}.shinyResult243{text-align:center;font-size:9px;margin:4px 0 7px;text-shadow:0 0 10px #ff8cc477}.win243{animation:win243 .55s ease 2}.lose243{animation:lose243 .6s ease}@keyframes win243{50%{transform:translateY(-9px) scale(1.04)}}@keyframes lose243{50%{transform:translateY(4px) scale(.97);opacity:.8}}`;document.head.appendChild(css);late243()
})();